version: '3.4'

services:
  organizer-postgres:
    image: postgres:12.1-alpine
    container_name: organizer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${HO_DB_DATABASE}"
      POSTGRES_USER: "${HO_DB_USER}"
      POSTGRES_PASSWORD: "${HO_DB_PASSWORD}"
    ports:
      - "${HO_DB_PORT}:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
      network.host: 0.0.0.0
      cluster.name: home-organizer
    ports:
      - "${HO_ELASTIC_PORT}:9200"
    networks:
      - elk

  logstash:
    image: logstash:7.6.0
    environment:
      http.host: 0.0.0.0
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.6.0
    ports:
      - target: 5601
        published: ${KIBANA_PUBLISHED_PORT}
    environment:
      server.name: kibana
      server.host: 0.0.0.0
      server.publicBaseUrl: "http://localhost:5601"
      monitoring.ui.container.elasticsearch.enabled: "true"
      elasticsearch.hosts: "http://elasticsearch:9200"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge