server:
  port: 8081
  error:
    include-message: always

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: ${HO_DB_SCHEMA}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    parameters:
      schema: ${spring.jpa.properties.hibernate.default_schema}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HO_DB_HOST}:${HO_DB_PORT}/${HO_DB_DATABASE}
    username: ${HO_DB_USER}
    password: ${HO_DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
  api-docs:
    path: /v1/api-docs

elasticsearch:
  host: ${HO_ELASTIC_HOST:localhost}:${HO_ELASTIC_PORT:9200}
